### ISSUE TITLE
Running both InversifySocketServer & InversifyExpressServer

### ISSUE THREAD

**Issue by matewilk** [alxshelepenok/inversify-socket-utils#160]
Hello,

I'm struggling to grasp the concept of having both `InversifyExpressServer` and `InversifySocketServer` running in parallel.

My App/Container/Express server config looks like this:

```js
import { app, error } from './app';

const container = new Container();
container
  .bind<SomeService>(TYPES.SomeService)
  .to(SomeService);

const server = new InversifyExpressServer(container);

server.setConfig(app);
server.setErrorConfig(error);

const serverInstance = server.build();

export { serverInstance };
```

How do I go about incorporating `InversifySocketServer` on the same port, is there any way I can just return an app and pass it as a second param to `InversifyExpressServer` or do I just create two separate servers, which wouldn't be ideal ...

**Comment by lndr27** [comment]
I faced the same dilemma and was able to make it work like this:

```typescript
//create inversify container
const container = new Container()
container.bind<Interfaces.Controller>(TYPE.Controller)
.to(MessageController)
.whenTargetNamed('MessageController')  // Needed since we'll have other express controllers

const inversifyExpressServer = new InversifyExpressServer(container)
inversifyExpressServer.setConfig((app) => {
    app.use(bodyParser.urlencoded({ extended: true }))
    app.use(bodyParser.json())
})

const app = inversifyExpressServer.build()
const httpServer = app.listen(config.PORT, () => {
    console.log(`listening to port ${config.PORT}`)
})
const socketServer = new InversifySocketServer(container, SocketIO(httpServer))
socketServer.build()
```

I don't know if it's the best solution since InversifyExpressServer changed controller binding, no longer needing @Inject decorator or manual binding.

**Comment by matewilk** [comment]
Thanks, looks promising. I'll look into my use case as it became a bit more complicated since I posted.

Nevertheless seems like the only option.

@lndr27 is `iocContainer` a typo? Should it just be `container`? If not, where is it coming from?

**Comment by lndr27** [comment]
> Thanks, looks promising. I'll look into my use case as it became a bit more complicated since I posted.
> 
> Nevertheless seems like the only option.
> 
> @lndr27 is `iocContainer` a typo? Should it just be `container`? If not, where is it coming from?

It’s a typo. Thanks for pointing that out. I fixed the code example.
